// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string DITestExtensionString = "E85F1C3F-9CCC-40EA-8040-79AC5723910D";
        public static Guid DITestExtension = new Guid(DITestExtensionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int DITestExtensionMainMenu = 0x1000;
        public const int DITestExtensionMainMenuGroup1 = 0x1100;
        public const int TestDependencyInjection = 0x0100;
    }
}